In [1]:
import numpy as np


## Funcion de NumPy mas usada en el mundo de data scienece

- creamos la cantidad **X** de filas y columnas, con valor **cero por defecto.**

In [8]:
my_list_3 = np.zeros(shape=(2,4), dtype=np.float128 )
my_list_3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float128)

- creamos la cantidad X de filas y columnas, con valor 1 por defecto

In [12]:
my_list_4 = np.ones(shape=(7, 5))
my_list_4

my_list_4[2, 3]

1.0

In [13]:
my_list_5 = np.linspace(start=0, stop=10, num=50, endpoint=False, )
my_list_5

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ,
       5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6,
       7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [5]:
my_list_6 = np.eye(4,7) 
my_list_6

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.]])

## De forma **aleatoria** cramos **array** con su **propia estructura.**

In [6]:
array = np.random.randint(1, 7, (4,7))
array[:, 0]


array([3, 4, 1, 3])

In [18]:
array = np.random.rand(1, 5, 22)
array

array([[[0.16135503, 0.77709836, 0.0761014 , 0.93542549, 0.77103417,
         0.67228925, 0.19660759, 0.74915651, 0.61508001, 0.03923481,
         0.15319975, 0.02100221, 0.04993921, 0.8263398 , 0.25268642,
         0.80124927, 0.58922392, 0.56520014, 0.7233906 , 0.79111225,
         0.29245502, 0.19597836],
        [0.61279094, 0.44325661, 0.19382314, 0.80476557, 0.14298477,
         0.30153418, 0.87664364, 0.408927  , 0.58459758, 0.31217675,
         0.66227167, 0.47759064, 0.48173126, 0.04840225, 0.76849348,
         0.88218562, 0.23284755, 0.12057797, 0.37641719, 0.65367969,
         0.67726666, 0.5256753 ],
        [0.69223184, 0.30020836, 0.44915668, 0.8421871 , 0.94070433,
         0.57598344, 0.96142617, 0.65600367, 0.76982563, 0.91561229,
         0.88244931, 0.20790536, 0.18377895, 0.3925403 , 0.63129909,
         0.20597786, 0.10019197, 0.97649237, 0.23604712, 0.26080336,
         0.19054573, 0.08768796],
        [0.67029329, 0.06551756, 0.1933878 , 0.26093862, 0.75294437,
 